[package]
name = "bevy-tower-defense"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.11.3", features = ["wav"] }
bevy-inspector-egui = "0.20.0"
bevy_mod_picking = "0.15.0"
